INFO 2020-02-28 19:21:03,046 autoreload 597 Watching for file changes with StatReloader
INFO 2020-02-28 19:21:43,440 autoreload 597 Watching for file changes with StatReloader
INFO 2020-02-28 19:24:48,916 autoreload 597 Watching for file changes with StatReloader
INFO 2020-02-28 19:59:43,447 autoreload 217 E:\forumPro\forumapi\forumapi\settings\dev.py changed, reloading.
INFO 2020-02-28 19:59:45,242 autoreload 597 Watching for file changes with StatReloader
INFO 2020-02-28 20:02:02,506 autoreload 217 E:\forumPro\forumapi\forumapi\settings\dev.py changed, reloading.
INFO 2020-02-28 20:02:04,415 autoreload 597 Watching for file changes with StatReloader
INFO 2020-02-28 20:05:13,775 autoreload 217 E:\forumPro\forumapi\forumapi\settings\dev.py changed, reloading.
INFO 2020-02-28 20:05:15,457 autoreload 597 Watching for file changes with StatReloader
INFO 2020-02-28 20:05:39,826 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 12:54:07,180 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 12:55:00,885 autoreload 217 E:\forumPro\forumapi\forumapi\settings\dev.py changed, reloading.
INFO 2020-03-02 12:55:02,800 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 13:09:15,501 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 13:10:27,495 autoreload 217 E:\forumPro\forumapi\forumapi\urls.py changed, reloading.
INFO 2020-03-02 13:10:29,498 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 13:10:38,328 autoreload 217 E:\forumPro\forumapi\forumapi\urls.py changed, reloading.
INFO 2020-03-02 13:10:40,441 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 13:12:07,338 autoreload 217 E:\forumPro\forumapi\forumapi\urls.py changed, reloading.
INFO 2020-03-02 13:12:09,345 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 13:12:54,773 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 13:13:18,524 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 13:13:42,655 autoreload 217 E:\forumPro\forumapi\forumapi\settings\dev.py changed, reloading.
INFO 2020-03-02 13:13:44,432 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 13:14:22,335 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 13:14:51,992 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-02 13:14:53,832 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 13:15:18,110 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 13:16:11,520 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 13:18:15,426 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 13:20:46,023 autoreload 217 E:\forumPro\forumapi\forumapi\settings\dev.py changed, reloading.
INFO 2020-03-02 13:30:37,158 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 13:31:10,250 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-03-02 13:31:41,143 log 228 Not Found: /
WARNING 2020-03-02 13:31:41,145 basehttp 154 "GET / HTTP/1.1" 404 2032
WARNING 2020-03-02 13:31:41,525 log 228 Not Found: /favicon.ico
WARNING 2020-03-02 13:31:41,526 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2083
WARNING 2020-03-02 13:32:46,736 log 228 Not Found: /
WARNING 2020-03-02 13:32:46,737 basehttp 154 "POST / HTTP/1.1" 404 2033
WARNING 2020-03-02 13:35:59,309 log 228 Not Found: /
WARNING 2020-03-02 13:35:59,310 basehttp 154 "POST / HTTP/1.1" 404 2033
WARNING 2020-03-02 13:36:20,458 log 228 Not Found: /users
WARNING 2020-03-02 13:36:20,459 basehttp 154 "POST /users HTTP/1.1" 404 2066
WARNING 2020-03-02 13:36:37,026 log 228 Not Found: /users
WARNING 2020-03-02 13:36:37,027 basehttp 154 "GET /users HTTP/1.1" 404 2065
WARNING 2020-03-02 13:36:43,761 log 228 Not Found: /users/
WARNING 2020-03-02 13:36:43,762 basehttp 154 "GET /users/ HTTP/1.1" 404 2121
INFO 2020-03-02 13:36:49,966 basehttp 154 "GET /users/login HTTP/1.1" 301 0
ERROR 2020-03-02 13:36:50,160 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 167, in http_method_not_allowed
    raise exceptions.MethodNotAllowed(request.method)
rest_framework.exceptions.MethodNotAllowed: Method "GET" not allowed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\settings.py", line 177, in import_from_string
    return import_string(val)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "e:\python3.666\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'renranapi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 459, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 298, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\settings.py", line 220, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'renranapi.utils.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'renranapi'.
ERROR 2020-03-02 13:36:50,166 basehttp 154 "GET /users/login/ HTTP/1.1" 500 139253
INFO 2020-03-02 13:38:44,578 autoreload 217 E:\forumPro\forumapi\forumapi\settings\dev.py changed, reloading.
INFO 2020-03-02 13:38:46,878 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-03-02 13:38:50,213 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\renderers.py", line 723, in render
    template = loader.get_template(self.template)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2020-03-02 13:38:50,218 basehttp 154 "GET /users/login/ HTTP/1.1" 500 86436
ERROR 2020-03-02 13:38:58,289 log 228 Internal Server Error: /users/login
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\middleware\common.py", line 53, in process_request
    path = self.get_full_path_with_slash(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\middleware\common.py", line 93, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.forum.cn:8000/users/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2020-03-02 13:38:58,291 basehttp 154 "POST /users/login HTTP/1.1" 500 68870
WARNING 2020-03-02 13:39:28,224 log 228 Bad Request: /users/login/
WARNING 2020-03-02 13:39:28,225 basehttp 154 "POST /users/login/ HTTP/1.1" 400 40
INFO 2020-03-02 13:39:34,073 basehttp 154 "POST /users/login/ HTTP/1.1" 200 177
WARNING 2020-03-02 17:55:35,419 log 228 Not Found: /
WARNING 2020-03-02 17:55:35,421 basehttp 154 "GET / HTTP/1.1" 404 2032
INFO 2020-03-02 18:19:48,897 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 18:21:27,788 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
WARNING 2020-03-02 18:21:28,088 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:21:28,090 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
INFO 2020-03-02 18:21:45,939 basehttp 154 "POST /users/login/ HTTP/1.1" 200 177
WARNING 2020-03-02 18:21:52,660 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:21:52,661 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
WARNING 2020-03-02 18:22:51,371 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:22:51,372 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
INFO 2020-03-02 18:24:06,652 basehttp 154 "POST /users/login/ HTTP/1.1" 200 177
INFO 2020-03-02 18:28:18,152 basehttp 154 "POST /users/login/ HTTP/1.1" 200 177
INFO 2020-03-02 18:28:43,498 basehttp 154 "POST /users/login/ HTTP/1.1" 200 177
INFO 2020-03-02 18:30:47,661 basehttp 154 "POST /users/login/ HTTP/1.1" 200 177
WARNING 2020-03-02 18:32:39,607 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:32:39,608 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
WARNING 2020-03-02 18:32:46,548 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:32:46,549 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
WARNING 2020-03-02 18:32:48,472 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:32:48,473 basehttp 154 "POST /users/login/ HTTP/1.1" 400 45
WARNING 2020-03-02 18:32:50,287 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:32:50,288 basehttp 154 "POST /users/login/ HTTP/1.1" 400 45
WARNING 2020-03-02 18:33:03,399 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:33:03,401 basehttp 154 "POST /users/login/ HTTP/1.1" 400 45
WARNING 2020-03-02 18:33:10,353 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:33:10,354 basehttp 154 "POST /users/login/ HTTP/1.1" 400 89
WARNING 2020-03-02 18:33:19,513 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:33:19,514 basehttp 154 "POST /users/login/ HTTP/1.1" 400 89
WARNING 2020-03-02 18:33:23,490 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:33:23,491 basehttp 154 "POST /users/login/ HTTP/1.1" 400 45
WARNING 2020-03-02 18:33:31,785 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:33:31,786 basehttp 154 "POST /users/login/ HTTP/1.1" 400 45
WARNING 2020-03-02 18:33:44,819 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:33:44,820 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
WARNING 2020-03-02 18:33:49,960 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:33:49,961 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
INFO 2020-03-02 18:33:53,386 basehttp 154 "POST /users/login/ HTTP/1.1" 200 177
INFO 2020-03-02 18:40:52,549 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-02 18:40:54,709 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 18:40:59,342 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-03-02 18:41:13,010 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:41:13,011 basehttp 154 "POST /users/login/ HTTP/1.1" 400 37
WARNING 2020-03-02 18:41:16,871 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:41:16,872 basehttp 154 "POST /users/login/ HTTP/1.1" 400 37
WARNING 2020-03-02 18:41:20,535 log 228 Bad Request: /users/login/
WARNING 2020-03-02 18:41:20,537 basehttp 154 "POST /users/login/ HTTP/1.1" 400 37
INFO 2020-03-02 18:42:03,150 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-02 18:42:05,085 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 18:42:14,070 basehttp 154 "POST /users/login/ HTTP/1.1" 200 177
INFO 2020-03-02 18:48:03,732 autoreload 217 E:\forumPro\forumapi\forumapi\settings\dev.py changed, reloading.
INFO 2020-03-02 18:48:07,091 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 19:16:04,901 autoreload 217 E:\forumPro\forumapi\forumapi\settings\dev.py changed, reloading.
INFO 2020-03-02 19:16:07,171 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-03-02 19:16:24,804 basehttp 154 "POST /users/login/ HTTP/1.1" 500 59
ERROR 2020-03-02 19:16:29,493 basehttp 154 "POST /users/login/ HTTP/1.1" 500 59
ERROR 2020-03-02 19:16:30,697 basehttp 154 "POST /users/login/ HTTP/1.1" 500 59
ERROR 2020-03-02 19:16:30,701 basehttp 154 "POST /users/login/ HTTP/1.1" 500 59
ERROR 2020-03-02 19:16:32,616 basehttp 154 "POST /users/login/ HTTP/1.1" 500 59
INFO 2020-03-02 19:16:48,174 autoreload 217 E:\forumPro\forumapi\forumapi\settings\dev.py changed, reloading.
INFO 2020-03-02 19:16:50,525 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-03-02 19:16:59,419 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\views.py", line 57, in post
    if serializer.is_valid():
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 234, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 436, in run_validation
    value = self.validate(value)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\serializers.py", line 50, in validate
    user = authenticate(**credentials)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 21, in load_backend
    return import_string(path)()
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "e:\python3.666\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\forumPro\forumapi\forumapi\apps\users\utils.py", line 2, in <module>
    from forumapi.apps.users import models
  File "E:\forumPro\forumapi\forumapi\apps\users\models.py", line 6, in <module>
    class User(AbstractUser):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\db\models\base.py", line 111, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class forumapi.apps.users.models.User doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
ERROR 2020-03-02 19:16:59,427 basehttp 154 "POST /users/login/ HTTP/1.1" 500 20367
INFO 2020-03-02 19:18:14,924 basehttp 154 "POST /users/login/ HTTP/1.1" 200 177
INFO 2020-03-02 19:20:45,350 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 19:20:51,731 basehttp 154 "POST /users/login/ HTTP/1.1" 200 177
INFO 2020-03-02 19:21:17,891 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\utils.py changed, reloading.
INFO 2020-03-02 19:21:20,635 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 19:22:08,163 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-03-02 19:22:12,050 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\views.py", line 57, in post
    if serializer.is_valid():
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 234, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 436, in run_validation
    value = self.validate(value)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\serializers.py", line 50, in validate
    user = authenticate(**credentials)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 21, in load_backend
    return import_string(path)()
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "e:\python3.666\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\forumPro\forumapi\forumapi\apps\users\utils.py", line 2, in <module>
    from forumapi.apps.users.models import User
  File "E:\forumPro\forumapi\forumapi\apps\users\models.py", line 6, in <module>
    class User(AbstractUser):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\db\models\base.py", line 111, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class forumapi.apps.users.models.User doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
ERROR 2020-03-02 19:22:12,058 basehttp 154 "POST /users/login/ HTTP/1.1" 500 20372
INFO 2020-03-02 19:22:54,510 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-03-02 19:22:55,848 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\views.py", line 57, in post
    if serializer.is_valid():
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 234, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 436, in run_validation
    value = self.validate(value)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\serializers.py", line 50, in validate
    user = authenticate(**credentials)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 21, in load_backend
    return import_string(path)()
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "e:\python3.666\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\forumPro\forumapi\forumapi\apps\users\utils.py", line 2, in <module>
    from forumapi.apps.users.models import User
  File "E:\forumPro\forumapi\forumapi\apps\users\models.py", line 6, in <module>
    class User(AbstractUser):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\db\models\base.py", line 111, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class forumapi.apps.users.models.User doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
ERROR 2020-03-02 19:22:55,855 basehttp 154 "POST /users/login/ HTTP/1.1" 500 20372
INFO 2020-03-02 19:24:49,145 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-03-02 19:24:53,156 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\utils\module_loading.py", line 20, in import_string
    return getattr(module, class_name)
AttributeError: module 'users.utils' has no attribute 'UsernameMobileAuthBackend'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\views.py", line 57, in post
    if serializer.is_valid():
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 234, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 436, in run_validation
    value = self.validate(value)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\serializers.py", line 50, in validate
    user = authenticate(**credentials)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 21, in load_backend
    return import_string(path)()
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\utils\module_loading.py", line 24, in import_string
    ) from err
ImportError: Module "users.utils" does not define a "UsernameMobileAuthBackend" attribute/class
ERROR 2020-03-02 19:24:53,161 basehttp 154 "POST /users/login/ HTTP/1.1" 500 19463
INFO 2020-03-02 19:25:16,095 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\utils.py changed, reloading.
INFO 2020-03-02 19:25:20,576 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-03-02 19:25:22,889 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\views.py", line 57, in post
    if serializer.is_valid():
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 234, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 436, in run_validation
    value = self.validate(value)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\serializers.py", line 50, in validate
    user = authenticate(**credentials)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 21, in load_backend
    return import_string(path)()
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "e:\python3.666\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\forumPro\forumapi\forumapi\apps\users\utils.py", line 2, in <module>
    from forumapi.apps.users.models import User
  File "E:\forumPro\forumapi\forumapi\apps\users\models.py", line 6, in <module>
    class User(AbstractUser):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\db\models\base.py", line 111, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class forumapi.apps.users.models.User doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
ERROR 2020-03-02 19:25:22,899 basehttp 154 "POST /users/login/ HTTP/1.1" 500 20372
INFO 2020-03-02 19:25:36,609 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 19:25:40,238 basehttp 154 "POST /users/login/ HTTP/1.1" 200 177
INFO 2020-03-02 19:26:18,753 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-03-02 19:26:25,100 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\views.py", line 57, in post
    if serializer.is_valid():
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 234, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 436, in run_validation
    value = self.validate(value)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\serializers.py", line 50, in validate
    user = authenticate(**credentials)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "E:\forumPro\forumapi\forumapi\apps\users\utils.py", line 12, in authenticate
    if isinstance(user,User) and user.check_password(password) and self.user_can_authenticate(user):
NameError: name 'User' is not defined
ERROR 2020-03-02 19:26:25,106 basehttp 154 "POST /users/login/ HTTP/1.1" 500 18829
INFO 2020-03-02 19:26:35,673 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\utils.py changed, reloading.
INFO 2020-03-02 19:26:41,163 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 19:26:43,095 basehttp 154 "POST /users/login/ HTTP/1.1" 200 177
INFO 2020-03-02 19:27:08,558 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-03-02 19:27:17,833 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\views.py", line 57, in post
    if serializer.is_valid():
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 234, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 436, in run_validation
    value = self.validate(value)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\serializers.py", line 50, in validate
    user = authenticate(**credentials)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 21, in load_backend
    return import_string(path)()
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "e:\python3.666\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\forumPro\forumapi\forumapi\apps\users\utils.py", line 2, in <module>
    from apps.users.models import User
ModuleNotFoundError: No module named 'apps'
ERROR 2020-03-02 19:27:17,843 basehttp 154 "POST /users/login/ HTTP/1.1" 500 19909
INFO 2020-03-02 19:28:11,964 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-03-02 19:28:37,685 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\views.py", line 57, in post
    if serializer.is_valid():
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 234, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 436, in run_validation
    value = self.validate(value)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\serializers.py", line 50, in validate
    user = authenticate(**credentials)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\contrib\auth\__init__.py", line 21, in load_backend
    return import_string(path)()
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "e:\python3.666\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\forumPro\forumapi\forumapi\apps\users\utils.py", line 2, in <module>
    from forumapi.apps.users.models import User
  File "E:\forumPro\forumapi\forumapi\apps\users\models.py", line 6, in <module>
    class User(AbstractUser):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\db\models\base.py", line 111, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class forumapi.apps.users.models.User doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
ERROR 2020-03-02 19:28:37,696 basehttp 154 "POST /users/login/ HTTP/1.1" 500 20372
INFO 2020-03-02 19:30:24,041 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 19:30:27,469 basehttp 154 "POST /users/login/ HTTP/1.1" 200 177
INFO 2020-03-02 19:31:41,773 basehttp 154 "POST /users/login/ HTTP/1.1" 200 199
INFO 2020-03-02 19:32:51,013 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 19:32:57,687 basehttp 154 "POST /users/login/ HTTP/1.1" 200 199
INFO 2020-03-02 19:34:08,572 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\utils.py changed, reloading.
INFO 2020-03-02 19:34:10,492 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 19:34:54,526 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-03-02 19:34:55,839 log 228 Bad Request: /users/login/
WARNING 2020-03-02 19:34:55,840 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
ERROR 2020-03-02 19:35:01,431 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\views.py", line 60, in post
    response_data = jwt_response_payload_handler(token, user, request)
  File "E:\forumPro\forumapi\forumapi\apps\users\utils.py", line 14, in jwt_response_payload_handler
    'avatar': user.avatar.url,
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\db\models\fields\files.py", line 61, in url
    self._require_file()
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\db\models\fields\files.py", line 38, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'avatar' attribute has no file associated with it.
ERROR 2020-03-02 19:35:01,435 basehttp 154 "POST /users/login/ HTTP/1.1" 500 18558
INFO 2020-03-02 19:37:19,638 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-03-02 19:37:20,646 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework_jwt\views.py", line 60, in post
    response_data = jwt_response_payload_handler(token, user, request)
  File "E:\forumPro\forumapi\forumapi\apps\users\utils.py", line 15, in jwt_response_payload_handler
    'nickname': user.nickname,
AttributeError: 'User' object has no attribute 'nickname'
ERROR 2020-03-02 19:37:20,651 basehttp 154 "POST /users/login/ HTTP/1.1" 500 18204
INFO 2020-03-02 19:38:00,061 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\models.py changed, reloading.
INFO 2020-03-02 19:38:02,162 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 19:38:35,567 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-02 19:38:41,621 basehttp 154 "POST /users/login/ HTTP/1.1" 200 256
INFO 2020-03-03 14:23:05,221 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 14:32:52,303 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
WARNING 2020-03-03 14:32:52,870 log 228 Bad Request: /users/login/
WARNING 2020-03-03 14:32:52,871 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
INFO 2020-03-03 14:33:16,372 basehttp 154 "POST /users/login/ HTTP/1.1" 200 256
INFO 2020-03-03 14:50:30,709 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-03 14:50:32,571 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 14:50:48,600 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-03 14:50:50,430 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 14:50:57,960 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-03 14:51:00,159 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 14:51:03,900 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-03 14:51:06,216 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 14:51:12,630 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-03 14:51:15,066 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 14:51:21,268 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-03 14:51:22,982 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 14:51:29,596 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-03 14:51:31,433 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 14:52:00,413 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-03 14:52:05,115 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 14:53:28,052 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-03 14:53:33,566 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 14:53:38,304 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\utils.py changed, reloading.
INFO 2020-03-03 14:53:40,136 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 14:54:31,244 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 14:54:32,929 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 14:56:49,226 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 14:56:51,553 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 14:59:59,680 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:00:02,078 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 15:02:23,971 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:02:25,716 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 15:02:34,864 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:02:37,677 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 15:03:34,098 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:03:36,085 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 15:04:29,718 basehttp 154 "GET /users/mobile/18434761073 HTTP/1.1" 301 0
INFO 2020-03-03 15:04:57,402 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-03-03 15:05:57,221 log 228 Internal Server Error: /users/mobile/18434761073/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\forumPro\forumapi\forumapi\apps\users\views.py", line 10, in get
    user = settings.AUTH_USER_MODEL.objects.get(mobile=mobile)
AttributeError: 'str' object has no attribute 'objects'
ERROR 2020-03-03 15:05:57,225 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 500 18170
ERROR 2020-03-03 15:06:02,214 log 228 Internal Server Error: /users/mobile/18434761073/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\forumPro\forumapi\forumapi\apps\users\views.py", line 10, in get
    user = settings.AUTH_USER_MODEL.objects.get(mobile=mobile)
AttributeError: 'str' object has no attribute 'objects'
ERROR 2020-03-03 15:06:02,216 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 500 18170
INFO 2020-03-03 15:20:25,425 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:20:27,427 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 15:21:23,382 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:21:29,375 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 15:23:11,223 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 200 31
INFO 2020-03-03 15:24:54,476 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:24:56,467 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 15:25:03,063 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 200 50
INFO 2020-03-03 15:33:18,181 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:33:20,226 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 15:33:46,366 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:33:48,879 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 15:34:17,435 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 15:34:30,202 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 200 50
INFO 2020-03-03 15:38:09,503 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 200 50
INFO 2020-03-03 15:38:20,692 basehttp 154 "GET /users/mobile/18434761074/ HTTP/1.1" 200 50
INFO 2020-03-03 15:38:54,476 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 200 50
INFO 2020-03-03 15:38:58,088 basehttp 154 "GET /users/mobile/18434761074/ HTTP/1.1" 200 50
INFO 2020-03-03 15:39:53,644 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:39:55,696 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 15:40:10,393 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:40:12,830 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 15:40:41,010 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:40:43,124 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-03-03 15:40:50,127 log 228 Bad Request: /users/mobile/18434761073/
WARNING 2020-03-03 15:40:50,128 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 400 50
WARNING 2020-03-03 15:41:07,244 log 228 Bad Request: /users/mobile/18434761073/
WARNING 2020-03-03 15:41:07,245 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 400 50
WARNING 2020-03-03 15:41:12,907 log 228 Bad Request: /users/mobile/18434761074/
WARNING 2020-03-03 15:41:12,909 basehttp 154 "GET /users/mobile/18434761074/ HTTP/1.1" 400 50
WARNING 2020-03-03 15:41:52,248 log 228 Bad Request: /users/mobile/18434761073/
WARNING 2020-03-03 15:41:52,249 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 400 50
WARNING 2020-03-03 15:44:10,128 log 228 Bad Request: /users/mobile/18434761073/
WARNING 2020-03-03 15:44:10,130 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 400 50
WARNING 2020-03-03 15:44:14,916 log 228 Bad Request: /users/mobile/18434761074/
WARNING 2020-03-03 15:44:14,917 basehttp 154 "GET /users/mobile/18434761074/ HTTP/1.1" 400 50
WARNING 2020-03-03 15:45:36,574 log 228 Bad Request: /users/mobile/18434767864/
WARNING 2020-03-03 15:45:36,575 basehttp 154 "GET /users/mobile/18434767864/ HTTP/1.1" 400 50
INFO 2020-03-03 15:46:37,468 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:46:39,405 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-03-03 15:46:58,377 log 228 Bad Request: /users/mobile/18434761077/
WARNING 2020-03-03 15:46:58,378 basehttp 154 "GET /users/mobile/18434761077/ HTTP/1.1" 400 50
INFO 2020-03-03 15:47:12,379 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:47:14,447 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-03-03 15:47:18,650 log 228 Bad Request: /users/mobile/18434761075/
WARNING 2020-03-03 15:47:18,651 basehttp 154 "GET /users/mobile/18434761075/ HTTP/1.1" 400 50
INFO 2020-03-03 15:47:45,696 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:47:48,067 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-03-03 15:47:49,959 log 228 Bad Request: /users/mobile/18434761088/
WARNING 2020-03-03 15:47:49,961 basehttp 154 "GET /users/mobile/18434761088/ HTTP/1.1" 400 50
INFO 2020-03-03 15:48:12,218 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-03-03 15:48:19,887 log 228 Bad Request: /users/mobile/18434761087/
WARNING 2020-03-03 15:48:19,888 basehttp 154 "GET /users/mobile/18434761087/ HTTP/1.1" 400 50
INFO 2020-03-03 15:49:03,628 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:49:05,808 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-03-03 15:49:10,492 log 228 Bad Request: /users/mobile/18434761073/
WARNING 2020-03-03 15:49:10,493 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 400 50
ERROR 2020-03-03 15:49:13,309 log 228 Internal Server Error: /users/mobile/18434761077/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\forumPro\forumapi\forumapi\apps\users\views.py", line 55, in get
    user = model.objects.get(mobile=mobile)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\db\models\query.py", line 408, in get
    self.model._meta.object_name
users.models.User.DoesNotExist: User matching query does not exist.
ERROR 2020-03-03 15:49:13,313 basehttp 154 "GET /users/mobile/18434761077/ HTTP/1.1" 500 18455
INFO 2020-03-03 15:49:42,212 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 15:49:44,661 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 15:49:47,985 basehttp 154 "GET /users/mobile/18463477874/ HTTP/1.1" 200 31
INFO 2020-03-03 16:42:09,634 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-03 16:42:11,739 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 16:43:27,156 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-03 16:43:29,048 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 16:43:49,791 basehttp 154 "OPTIONS /users/login/ HTTP/1.1" 200 0
WARNING 2020-03-03 16:43:49,815 log 228 Bad Request: /users/login/
WARNING 2020-03-03 16:43:49,816 basehttp 154 "POST /users/login/ HTTP/1.1" 400 68
INFO 2020-03-03 16:44:05,157 basehttp 154 "POST /users/login/ HTTP/1.1" 200 256
INFO 2020-03-03 16:53:27,365 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-03 16:53:29,265 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 16:55:01,564 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\urls.py changed, reloading.
INFO 2020-03-03 16:55:03,539 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 16:55:59,700 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 16:56:01,739 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 16:57:07,527 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 16:57:09,311 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 16:57:40,944 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 16:57:42,646 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 16:57:52,102 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 16:57:54,788 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:00:49,114 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 17:00:50,930 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:01:16,842 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:01:18,693 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:01:25,045 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:01:27,517 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:01:36,157 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:01:38,163 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:01:51,395 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:01:53,215 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:02:14,985 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:02:16,965 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:02:52,147 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:02:53,808 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:03:15,647 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:03:17,865 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:03:34,028 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:03:36,140 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:03:47,967 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:03:49,663 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:04:06,433 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:04:08,135 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:04:30,171 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:04:32,121 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:04:49,690 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:04:51,428 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:05:16,350 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:05:18,419 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:05:39,203 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:05:40,991 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:05:46,291 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:05:48,321 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:06:11,064 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:06:13,205 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:07:34,916 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:07:37,046 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:08:01,509 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:08:03,526 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:08:17,338 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:08:19,586 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:08:30,134 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:08:32,647 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:08:55,648 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:08:57,615 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:13:01,388 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\utils.py changed, reloading.
INFO 2020-03-03 17:13:03,061 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:13:33,727 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:13:35,437 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:14:01,218 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:14:03,097 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:15:23,313 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:15:25,603 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:15:33,688 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:15:35,753 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:15:49,274 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:15:51,404 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:16:27,579 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:16:30,016 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:16:44,030 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:16:45,695 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:23:18,140 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:23:20,096 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:23:35,017 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:23:37,489 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:23:41,232 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:23:43,511 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:23:53,821 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:23:55,938 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:24:31,367 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\serializers.py changed, reloading.
INFO 2020-03-03 17:24:33,146 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:24:51,793 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-03-03 17:25:16,088 log 228 Bad Request: /users/mobile/19434761073/
WARNING 2020-03-03 17:25:16,090 basehttp 154 "GET /users/mobile/19434761073/ HTTP/1.1" 400 50
INFO 2020-03-03 17:26:50,480 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 200 31
INFO 2020-03-03 17:27:33,160 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 200 31
INFO 2020-03-03 17:27:40,197 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 200 31
INFO 2020-03-03 17:29:17,637 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 200 31
INFO 2020-03-03 17:29:48,782 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 200 31
INFO 2020-03-03 17:30:09,394 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 200 31
INFO 2020-03-03 17:32:17,420 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 200 31
INFO 2020-03-03 17:32:47,468 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 200 31
INFO 2020-03-03 17:39:26,786 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\views.py changed, reloading.
INFO 2020-03-03 17:39:28,610 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:39:39,091 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 200 31
INFO 2020-03-03 17:40:10,234 autoreload 217 E:\forumPro\forumapi\forumapi\apps\users\utils.py changed, reloading.
INFO 2020-03-03 17:40:12,390 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-03-03 17:40:19,005 log 228 Bad Request: /users/mobile/18434761073/
WARNING 2020-03-03 17:40:19,006 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 400 50
WARNING 2020-03-03 17:41:02,656 log 228 Bad Request: /users/mobile/18434761073/
WARNING 2020-03-03 17:41:02,658 basehttp 154 "GET /users/mobile/18434761073/ HTTP/1.1" 400 50
INFO 2020-03-03 17:41:07,025 basehttp 154 "GET /users/mobile/18434761074/ HTTP/1.1" 200 31
INFO 2020-03-03 17:41:19,295 basehttp 154 "OPTIONS /users/register/ HTTP/1.1" 200 0
ERROR 2020-03-03 17:41:19,592 log 228 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 234, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 433, in run_validation
    value = self.to_internal_value(data)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 486, in to_internal_value
    for field in fields:
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 369, in _writable_fields
    for field in self.fields.values():
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 363, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 1020, in get_fields
    serializer_class=self.__class__.__name__
AssertionError: Class RegisterModelSerializer missing "Meta.model" attribute
ERROR 2020-03-03 17:41:19,596 basehttp 154 "POST /users/register/ HTTP/1.1" 500 19444
INFO 2020-03-03 17:42:07,684 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-03-03 17:42:09,885 log 228 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 234, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\WO\Envs\forumPro\lib\site-packages\rest_framework\serializers.py", line 436, in run_validation
    value = self.validate(value)
  File "E:\forumPro\forumapi\forumapi\apps\users\serializers.py", line 22, in validate
    if not re.match("1[3-9]\d{9}", attrs).get("mobile"):
  File "e:\python3.666\lib\re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
ERROR 2020-03-03 17:42:09,893 basehttp 154 "POST /users/register/ HTTP/1.1" 500 18859
INFO 2020-03-03 17:42:34,293 autoreload 597 Watching for file changes with StatReloader
INFO 2020-03-03 17:42:37,191 basehttp 154 "POST /users/register/ HTTP/1.1" 201 252
INFO 2020-03-03 17:45:06,095 basehttp 154 "GET /users/mobile/18434779966/ HTTP/1.1" 200 31
INFO 2020-03-03 17:45:12,290 basehttp 154 "POST /users/register/ HTTP/1.1" 201 254
